player_only: "[EssentialsPlus] That command can only be executed by players"
value_too_big: "[EssentialsPlus] Provided number was too big"
value_nan: "[EssentialsPlus] The provided value was not a number"

fly:
  enabled: "[EssentialsPlus] Fly has been enabled"
  disabled: "[EssentialsPlus] Fly has been disabled"

blocktrail:
  enabled: "[EssentialsPlus] Blocktrail has been enabled"
  disabled: "[EssentialsPlus] Blocktrail has been disabled"

heal:
  healed: "[EssentialsPlus] You have been healed"

bedwars:
  bw-lighthouse:
    teams:
      red: "RED"
      blue: "BLUE"
      green: "GREEN"
      yellow: "YELLOW"
      aqua: "AQUA"
      white: "WHITE"
      pink: "LIGHT_PURPLE"
      gray: "DARK_GRAY"

    spawn_points:
      wait:
        x: 0
        y: 118
        z: 0
      red:
        x: -23
        y: 65
        z: -87
      blue:
        x:
        y:
        z:
      green:
        x:
        y:
        z:
      yellow:
        x:
        y:
        z:
      aqua:
        x:
        y:
        z:
      white:
        x:
        y:
        z:
      pink:
        x:
        y:
        z:
      gray:
        x:
        y:
        z:
    generators:
      base:
        red:
          x: -23
          y: 64.5
          z: -91
        blue:
          x:
          y:
          z:
        green:
          x:
          y:
          z:
        yellow:
          x:
          y:
          z:
        aqua:
          x:
          y:
          z:
        white:
          x:
          y:
          z:
        pink:
          x:
          y:
          z:
        gray:
          x:
          y:
          z:
      diamond:
        1:
          x: -32
          y: 65
          z: -32
        2:
          x: 32
          y: 65
          z: -32
        3:
          x: 32
          y: 65
          z: 32
        4:
          x: -32
          y: 65
          z: 32
      emerald:
        1:
          x: -12
          y: 66
          z: 15
        2:
          x: -3
          y: 56
          z: 8
        3:
          x: 3
          y: 56
          z: -8
        4:
          x: 12
          y: 66
          z: -15
    beds:
      red:
        x: -23
        y: 66
        z: -75
      blue:
        x: 32
        y: 67
        z: -70
      green:
        x: 70
        y: 67
        z: -32
      yellow:
        x: 70
        y: 67
        z: 32
      aqua:
        x: 32
        y: 67
        z: 70
      white:
        x: -32
        y: 67
        z: 70
      pink:
        x: -70
        y: 67
        z: 32
      gray:
        x: -70
        y: 67
        z: -32

shrinkingcircle:
  gui:
    1:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    2:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    3:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    4:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    5:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    6:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    7:
      item: RED_DYE
      item_off: GRAY_DYE
      name: 'Manual'
      lore: ''
    8:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    9:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    10:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    11:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    12:
      item: TORCH
      name: 'Circle Radius'
      lore: ''
    13:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    14:
      item: EMERALD
      name: 'Shrink Size'
      lore: ''
    15:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    16:
      item: REDSTONE
      item_off: GUNPOWDER
      name: 'Automatic'
      lore: ''
    17:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    18:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    19:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    20:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    21:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    22:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    23:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    24:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    25:
      item: WITHER_SKELETON_SKULL
      item_off: SKELETON_SKULL
      name: 'On Death'
      lore: ''
    26:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    27:
      item: NETHER_STAR
      name: 'Start'
      lore: ''

lavafloor:
  gui:
    1:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    2:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    3:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    4:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    5:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    6:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    7:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    8:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    9:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    10:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    11:
      item: LAVA_BUCKET
      name: 'Material'
      lore: ''
    12:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    13:
      item: SNOW
      name: 'Start Layer'
      lore: ''
    14:
      item: WHITE_STAINED_GLASS_PANE
      name: 'Shrink Size'
      lore: ''
    15:
      item: CLOCK
      name: 'Rise Time'
      lore: ''
    16:
      item: WHITE_STAINED_GLASS_PANE
      name: 'Shrink Size'
      lore: ''
    17:
      item: BARRIER
      name: 'Border Size'
      lore: ''
    18:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    19:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    20:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    21:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    22:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    23:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    24:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    25:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    26:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    27:
      item: NETHER_STAR
      name: 'Start'
      lore: ''
