player_only: '[EssentialsPlus] That command can only be executed by players'
value_too_big: '[EssentialsPlus] Provided number was too big'
value_nan: '[EssentialsPlus] The provided value was not a number'

fly:
  enabled: '[EssentialsPlus] Fly has been enabled'
  disabled: '[EssentialsPlus] Fly has been disabled'

blocktrail:
  enabled: '[EssentialsPlus] Blocktrail has been enabled'
  disabled: '[EssentialsPlus] Blocktrail has been disabled'

heal:
  healed: '[EssentialsPlus] You have been healed'

bedwars:
  footer_message: 'play.exampleserver.net'

  generators:
    base: 1
    diamond: 30
    emerald: 64

  events:
    diamond_2:
      time: 6
      message: 'Diamonds II'
    emerald_2:
      time: 6
      message: 'Emeralds II'
    diamond_3:
      time: 6
      message: 'Diamonds III'
    emerald_3:
      time: 6
      message: 'Emeralds III'
    beds_destroyed:
      time: 6
      message: 'Beds Destroyed'
    sudden_death:
      time: 10
      message: 'Sudden Death'
    game_over:
      time: 10
      message: 'Game Over'

  shops:
    item_shop:
      header:
        1:
          item: 'NETHER_STAR'
          name: 'Back to Quick Buy'
          type: 'category'
          caragory: 'general'
        2:
          item: 'TERRACOTTA'
          name: 'Blocks'
          type: 'category'
          category: 'blocks'
        3:
          item: 'GOLDEN_SWORD'
          name: 'Weapons'
          type: 'category'
          category: 'weapons'
        4:
          item: 'CHAINMAIL_BOOTS'
          name: 'Armour'
          type: 'category'
          category: 'armour'
        5:
          item: 'STONE_PICKAXE'
          name: 'Tools'
          type: 'category'
          category: 'tools'
        6:
          item: 'BOW'
          name: 'Bows'
          type: 'category'
          category: 'Bow'
        7:
          item: 'BREWING_STAND'
          type: 'category'
          name: 'Potions'
          category: 'potions'
        8:
          item: 'TNT'
          name: 'Utilities'
          type: 'category'
          category: 'utilities'
        11:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        12:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        13:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        14:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        15:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        16:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'
        17:
          item: 'BLACK_STAINED_GLASS_PANE'
          type: 'filler'
          name: '↑ Categories ↓ Items'

      general:
        20:
          item: 'WHITE_WOOL'
          name: 'Wool'
          type: 'buy'
          cost: 4
          count: 16
          material: 'IRON_INGOT'
        21:
          item: 'STONE_SWORD'
          name: 'Stone Sword'
          type: 'buy'
          cost: 10
          material: 'IRON_INGOT'
        22:
          item: 'CHAINMAIL_BOOTS'
          name: 'Permanent Chainmail Armour'
          type: 'buy'
          cost: 40
          material: 'IRON_INGOT'
        23:
          item: 'WOODEN_PICKAXE'
          name: 'Wooden Pickaxe'
          type: 'buy'
          cost: 10
          material: 'IRON_INGOT'
        24:
          item: 'BOW'
          name: 'Bow'
          type: 'buy'
          cost: 12
          material: 'GOLD_INGOT'
        25:
          item: 'POTION'
          name: 'Invisibility Potion (30:00)'
          type: 'buy'
          potion_type: 'INVISIBILITY'
          cost: 2
          material: 'EMERALD'
        26:
          item: 'TNT'
          name: 'TNT'
          type: 'buy'
          cost: 5
          material: 'GOLD_INGOT'
        29:
          item: 'OAK_PLANKS'
          name: 'Wood'
          type: 'buy'
          count: 16
          cost: 4
          material: 'GOLD_INGOT'
        30:
          item: 'IRON_SWORD'
          name: 'Iron Sword'
          type: 'buy'
          cost: 7
          material: 'GOLD_INGOT'
        31:
          item: 'IRON_BOOTS'
          name: 'Permanent Iron Armour'
          type: 'buy'
          cost: 12
          material: 'GOLD_INGOT'
        32:
          item: 'SHEARS'
          name: 'Shears'
          type: 'buy'
          cost: 20
          material: 'IRON_INGOT'
        33:
          item: 'ARROW'
          name: 'Arrow'
          type: 'buy'
          count: 2
          cost: 2
          material: 'GOLD_INGOT'
        34:
          item: 'POTION'
          name: 'Speed Potion (45:00)'
          type: 'buy'
          potion_type: 'SPEED'
          cost: 1
          material: 'EMERALD_INGOT'
        35:
          item: 'WATER'
          name: 'Water'
          type: 'buy'
          cost: 3
          material: 'GOLD_INGOT'
      blocks:
        21:
          item: 'WHITE_WOOL'
          name: 'Wool'
          type: 'buy'
          cost: 4
          count: 16
          material: 'IRON_INGOT'
        22:
          item: 'SMOOTH_SANDSTONE'
          name: 'Sandstone'
          type: 'buy'
          cost: 12
          count: 16
          material: 'IRON_INGOT'
        23:
          item: 'END_STONE'
          name: 'End Stone'
          type: 'buy'
          cost: 24
          count: 16
          material: 'IRON_INGOT'
        24:
          item: 'OAK_PLANKS'
          name: 'Wood'
          type: 'buy'
          cost: 4
          count: 16
          material: 'GOLD_INGOT'
        25:
          item: 'OBSIDIAN'
          name: 'Obsidian'
          type: 'buy'
          cost: 4
          count: 4
          material: 'EMERALD'
      weapons:
      tools:
      bows:
      potions:
      utilities:

  bw-lighthouse:
    teams:
      red: 'RED'
      blue: 'BLUE'
      green: 'GREEN'
      yellow: 'YELLOW'
      aqua: 'AQUA'
      white: 'WHITE'
      pink: 'LIGHT_PURPLE'
      gray: 'DARK_GRAY'

    spawn_points:
      wait:
        x: 0
        y: 118
        z: 0
      red:
        x: -23
        y: 65
        z: -87
      blue:
        x: 29
        y: 65
        z: -87
      green:
        x: 90
        y: 65
        z: -26
      yellow:
        x: 90 65
        y: 65
        z: 26
      aqua:
        x: 29
        y: 65
        z: 87
      white:
        x: -23
        y: 65
        z: 87
      pink:
        x: -84
        y: 65
        z: 26
      gray:
        x: -84
        y: 65
        z: -26
    generators:
      base:
        red:
          x: -22.5
          y: 64.5
          z: -90.5
        blue:
          x: 29.5
          y: 64.5
          z: -90.5
        green:
          x: 94.5
          y: 64.5
          z: -25.5
        yellow:
          x: 94.5
          y: 64.5
          z: 26.5
        aqua:
          x: 29.5
          y: 64.5
          z: 91.5
        white:
          x: -22.5
          y: 64.5
          z: 91.5
        pink:
          x: -87.5
          y: 64.5
          z: 26.5
        gray:
          x: -87.5
          y: 64.5
          z: -25.5
      diamond:
        1:
          x: -48.5
          y: 67
          z: -51.5
        2:
          x: 55.5
          y: 67
          z: -51.5
        3:
          x: 55.5
          y: 67
          z: 52.5
        4:
          x: -48.5
          y: 67
          z: 52.5
      emerald:
        1:
          x: 13.5
          y: 65
          z: -13.5
        2:
          x: -6.5
          y: 65
          z: 14.5
        3:
          x: 3.5
          y: 87
          z: -6.5
        4:
          x: 3.5
          y: 87
          z: 7.5
    beds:
      red:
        x: -23
        y: 66
        z: -75
      blue:
        x: 26
        y: 66
        z: -75
      green:
        x: 78
        y: 66
        z: -26
      yellow:
        x: 78
        y: 66
        z: 26
      aqua:
        x: 29
        y: 66
        z: 75
      white:
        x: -23
        y: 66
        z: 75
      pink:
        x: -72
        y: 66
        z: 26
      gray:
        x: -72
        y: 66
        z: -26


shrinkingcircle:
  gui:
    1:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    2:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    3:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    4:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    5:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    6:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    7:
      item: RED_DYE
      item_off: GRAY_DYE
      name: 'Manual'
      lore: ''
    8:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    9:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    10:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    11:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    12:
      item: TORCH
      name: 'Circle Radius'
      lore: ''
    13:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    14:
      item: EMERALD
      name: 'Shrink Size'
      lore: ''
    15:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    16:
      item: REDSTONE
      item_off: GUNPOWDER
      name: 'Automatic'
      lore: ''
    17:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    18:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    19:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    20:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    21:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    22:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    23:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    24:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    25:
      item: WITHER_SKELETON_SKULL
      item_off: SKELETON_SKULL
      name: 'On Death'
      lore: ''
    26:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    27:
      item: NETHER_STAR
      name: 'Start'
      lore: ''

lavafloor:
  gui:
    1:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    2:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    3:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    4:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    5:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    6:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    7:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    8:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    9:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    10:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    11:
      item: LAVA_BUCKET
      name: 'Material'
      lore: ''
    12:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    13:
      item: SNOW
      name: 'Start Layer'
      lore: ''
    14:
      item: WHITE_STAINED_GLASS_PANE
      name: 'Shrink Size'
      lore: ''
    15:
      item: CLOCK
      name: 'Rise Time'
      lore: ''
    16:
      item: WHITE_STAINED_GLASS_PANE
      name: 'Shrink Size'
      lore: ''
    17:
      item: BARRIER
      name: 'Border Size'
      lore: ''
    18:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    19:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    20:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    21:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    22:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    23:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    24:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    25:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    26:
      item: WHITE_STAINED_GLASS_PANE
      name: ''
      lore: ''
    27:
      item: NETHER_STAR
      name: 'Start'
      lore: ''
